version: '3.8'

services:
  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: liga2021
    volumes:
      - ./src/main/resources/db:/var/lib/postgresql/data
    ports:
      - 5432:5432