CREATE TABLE IF NOT EXISTS school(
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(100),
                       address VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS users(
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100),
                        age INT,
                        gender CHAR(1),
                        CONSTRAINT check_gender CHECK
                            (gender IN ('М', 'Ж')),
                        school_id INT,
                        FOREIGN KEY (school_id) REFERENCES school(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS post(
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        content VARCHAR(2048),
                        user_id INT,
                        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friends(
                                user_id INT,
                                user2_id INT,
                                FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                                FOREIGN KEY (user2_id) REFERENCES users(id) ON DELETE CASCADE
);