CREATE TABLE IF NOT EXISTS roles(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100)
    );



CREATE TABLE IF NOT EXISTS users(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100),
    password VARCHAR(100),
    role_id INT,
    FOREIGN KEY (role_id) REFERENCES roles(id)
    );
CREATE TABLE IF NOT EXISTS reserves(
                                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       date DATE,
                                       active boolean,
                                       user_id INT,
                                       FOREIGN KEY (user_id) REFERENCES users(id)
    );
INSERT INTO roles VALUES(1, 'ROLE_ADMIN');
INSERT INTO roles VALUES(2, 'ROLE_USER');